//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USP.Context
{
    using Models.Entity;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class K3CloudEntities : DbContext
    {
        public K3CloudEntities()
            : base("name=K3CloudEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_BD_SUPPLIER> T_BD_SUPPLIER { get; set; }
        public virtual DbSet<T_BD_SUPPLIER_L> T_BD_SUPPLIER_L { get; set; }
        public virtual DbSet<T_BD_SUPPLIERGROUP> T_BD_SUPPLIERGROUP { get; set; }
        public virtual DbSet<T_BD_SUPPLIERGROUP_L> T_BD_SUPPLIERGROUP_L { get; set; }
    }
}
