//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace USP.Models.ViewModel
{
    
    
    public class T_BD_SUPPLIERMetaData
    {
        [Required] 
        public virtual int FSUPPLIERID
        {
            get;
            set;
        }
        [Required] 
        public virtual int FMASTERID
        {
            get;
            set;
        }
        [Required] 
        public virtual int FCREATEORGID
        {
            get;
            set;
        }
        [Required] 
        public virtual int FUSEORGID
        {
            get;
            set;
        }
        [Required] 
        public virtual int FCREATORID
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FCREATEDATE
        {
            get;
            set;
        }
        [Required] 
        public virtual int FMODIFIERID
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FMODIFYDATE
        {
            get;
            set;
        }
    	
        [StringLength(1, ErrorMessage="最多可输入1个字符")]
        [Required] 
        public virtual string FDOCUMENTSTATUS
        {
            get;
            set;
        }
    	
        [StringLength(1, ErrorMessage="最多可输入1个字符")]
        [Required] 
        public virtual string FFORBIDSTATUS
        {
            get;
            set;
        }
        [Required] 
        public virtual int FAUDITORID
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FAUDITDATE
        {
            get;
            set;
        }
        [Required] 
        public virtual int FFORBIDERID
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FFORBIDDATE
        {
            get;
            set;
        }
    	
        [StringLength(255, ErrorMessage="最多可输入255个字符")]
        [Required] 
        public virtual string FNUMBER
        {
            get;
            set;
        }
    	
        [StringLength(10, ErrorMessage="最多可输入10个字符")]
        [Required] 
        public virtual string FSHORTNUMBER
        {
            get;
            set;
        }
        public virtual Nullable<int> FPRIMARYGROUP
        {
            get;
            set;
        }
        [Required] 
        public virtual int FCORRESPONDORGID
        {
            get;
            set;
        }
    }
}
