//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace USP.Models.ViewModel
{
    
    
    public class T_ORG_ORGANIZATIONSMetaData
    {
        [Required] 
        public virtual int FORGID
        {
            get;
            set;
        }
    	
        [StringLength(30, ErrorMessage="最多可输入30个字符")]
        [Required] 
        public virtual string FNUMBER
        {
            get;
            set;
        }
        [Required] 
        public virtual int FORGFORMID
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string FCONTACT
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="最多可输入100个字符")]
        [Required] 
        public virtual string FTEL
        {
            get;
            set;
        }
    	
        [StringLength(255, ErrorMessage="最多可输入255个字符")]
        [Required] 
        public virtual string FADDRESS
        {
            get;
            set;
        }
    	
        [StringLength(255, ErrorMessage="最多可输入255个字符")]
        [Required] 
        public virtual string FORGFUNCTIONS
        {
            get;
            set;
        }
    	
        [StringLength(1, ErrorMessage="最多可输入1个字符")]
        [Required] 
        public virtual string FISACCOUNTORG
        {
            get;
            set;
        }
    	
        [StringLength(1, ErrorMessage="最多可输入1个字符")]
        [Required] 
        public virtual string FISBUSINESSORG
        {
            get;
            set;
        }
    	
        [StringLength(30, ErrorMessage="最多可输入30个字符")]
        [Required] 
        public virtual string FACCTORGTYPE
        {
            get;
            set;
        }
        [Required] 
        public virtual int FPARENTID
        {
            get;
            set;
        }
        [Required] 
        public virtual int FCREATORID
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FCREATEDATE
        {
            get;
            set;
        }
        [Required] 
        public virtual int FMODIFIERID
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FMODIFYDATE
        {
            get;
            set;
        }
    	
        [StringLength(1, ErrorMessage="最多可输入1个字符")]
        [Required] 
        public virtual string FFORBIDSTATUS
        {
            get;
            set;
        }
        [Required] 
        public virtual int FFORBIDORID
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FFORBIDDATE
        {
            get;
            set;
        }
    	
        [StringLength(1, ErrorMessage="最多可输入1个字符")]
        [Required] 
        public virtual string FDOCUMENTSTATUS
        {
            get;
            set;
        }
    	
        [StringLength(1, ErrorMessage="最多可输入1个字符")]
        [Required] 
        public virtual string FISSYSPRESET
        {
            get;
            set;
        }
        [Required] 
        public virtual int FAUDITORID
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> FAUDITDATE
        {
            get;
            set;
        }
        public virtual Nullable<int> FACCTGRANGEID
        {
            get;
            set;
        }
    	
        [StringLength(20, ErrorMessage="最多可输入20个字符")]
        public virtual string FVALUATIONMETHOD
        {
            get;
            set;
        }
        public virtual Nullable<int> FACCTGORGID
        {
            get;
            set;
        }
        public virtual Nullable<int> FACCTGSYSTEMID
        {
            get;
            set;
        }
    	
        [StringLength(20, ErrorMessage="最多可输入20个字符")]
        public virtual string FDIVIDEDBASIS
        {
            get;
            set;
        }
        public virtual Nullable<int> FACCTPOLICYID
        {
            get;
            set;
        }
    	
        [StringLength(30, ErrorMessage="最多可输入30个字符")]
        public virtual string FPOSTCODE
        {
            get;
            set;
        }
        [Required] 
        public virtual decimal FPOINTSRATE
        {
            get;
            set;
        }
    }
}
