//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(USP.Models.ViewModel.T_ORG_ORGANIZATIONSMetaData))]
    public partial class T_ORG_ORGANIZATIONS
    {
        public int FORGID { get; set; }
        public string FNUMBER { get; set; }
        public int FORGFORMID { get; set; }
        public string FCONTACT { get; set; }
        public string FTEL { get; set; }
        public string FADDRESS { get; set; }
        public string FORGFUNCTIONS { get; set; }
        public string FISACCOUNTORG { get; set; }
        public string FISBUSINESSORG { get; set; }
        public string FACCTORGTYPE { get; set; }
        public int FPARENTID { get; set; }
        public int FCREATORID { get; set; }
        public Nullable<System.DateTime> FCREATEDATE { get; set; }
        public int FMODIFIERID { get; set; }
        public Nullable<System.DateTime> FMODIFYDATE { get; set; }
        public string FFORBIDSTATUS { get; set; }
        public int FFORBIDORID { get; set; }
        public Nullable<System.DateTime> FFORBIDDATE { get; set; }
        public string FDOCUMENTSTATUS { get; set; }
        public string FISSYSPRESET { get; set; }
        public int FAUDITORID { get; set; }
        public Nullable<System.DateTime> FAUDITDATE { get; set; }
        public Nullable<int> FACCTGRANGEID { get; set; }
        public string FVALUATIONMETHOD { get; set; }
        public Nullable<int> FACCTGORGID { get; set; }
        public Nullable<int> FACCTGSYSTEMID { get; set; }
        public string FDIVIDEDBASIS { get; set; }
        public Nullable<int> FACCTPOLICYID { get; set; }
        public string FPOSTCODE { get; set; }
        public decimal FPOINTSRATE { get; set; }
    }
}
